FROM python:3.10-slim

# install python
# RUN apk update
# RUN apk add py-pip
# RUN apk add --no-cache python3-dev
# RUN pip3 install --upgrade pip

# move contents
WORKDIR /working
COPY . /working

# install requirements
RUN pip3 --no-cache-dir install -r requirements.txt

# expose flask 8080 port for ingress
EXPOSE 8080

CMD ["python3", "app.py"]
