apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: default
  labels:
    app: logstash
data:
  logstash.yml: |
     # no contents are in here
  pipelines.yml: |
    - pipeline.id: main
      path.config: "/usr/share/logstash/pipeline/*.conf"
