# Service for the Logstash Network
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
    - port: 514
      targetPort: 514
      nodePort: 30007

---
# Configuration of the Logstash
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: default
  labels:
    app: logstash
data:
  logstash.yml: |
     # no contents are in here
  pipelines.yml: |
    - pipeline.id: main
      path.config: "/usr/share/logstash/pipeline/*.conf"

---
# Deployment and Pod template of Logstash containers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  labels:
    app: logstash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash-instance
        image: docker.elastic.co/logstash/logstash:8.11.1
        ports:
        - containerPort: 514

        volumeMounts:
        # path for the pipeline/*.conf
        - name: pipelines-conf
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        # config yaml
        - name: logstash-config
          mountPath: /usr/share/logstash/config

      volumes:
      # this is the pipelines for the logstash
      - name: pipelines-conf
        hostPath:
          path: /data/pipeline
          type: Directory

      # these are the yml files that defined in ConfigMap: config_map.yaml
      - name: logstash-config
        configMap:
          name: logstash-configmap
          items:
            - key: pipelines.yml
              path: pipelines.yml
            - key: logstash.yml
              path: logstash.yml
