apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: blue

  template:
    metadata:
      labels:
        app: nginx
        version: blue

    spec:
      containers:
      - name: nginx
        image: localhost/nginx:blue
        ports:
        - containerPort: 80
