FROM ubuntu:latest

ARG SNOWCLI="https://sfc-repo.azure.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowflake-snowsql-1.2.10-1.x86_64.rpm"

# arguments controlling /scripts/setup.sql
ARG APP_STREAMLIT_SCHEMA="STREAMLIT_APP"

RUN apt-get update\
    && apt-get -y install\
    && apt-get install -y curl rpm

RUN curl -o snowsql ${SNOWCLI}
RUN rpm -i snowsql


ENV SNOWSQL_PWD="xxxx"
ENV SNOWSQL_ACCOUNT="qwdbrlw-xv35983"
ENV SNOWSQL_USER='tobytoyin03'
ENV SNOWSQL_DATABASE="PROD"
ENV SNOWSQL_SCHEMA="PUBLIC"

# build arg to env
ENV APP_STREAMLIT_SCHEMA=${APP_STREAMLIT_SCHEMA}
