services:
  app:
    container_name: app
    init: true
    volumes:
    - ./:/working
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    working_dir: /working

    build:
      context: .
      dockerfile: dockerfile.dev
      args: 
        - PYTHON_VERSION=3.12
        - DEP_MANAGER=poetry
    tty: true
    stdin_open: true


