FROM debian:latest


ENV DEBIAN_FRONTEND=noninteractive
# use bash not sh
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y software-properties-common
RUN apt-get install -y curl vim

WORKDIR /home/app/
COPY . /home/app/
