version: '3.8'

services:
  # build the backend container
  backend:
    build: ./backend/
    container_name: flask-backend
    ports:
      - 8080:8080
    networks:
      - api-network

  # build the client container, which access from backend
  client:
    build: ./client/
    container_name: flask-client
    environment:
      - URL=flask-backend  # same as the container_name in "services.backend"
    ports:
      - 8082:8082
    networks:
      - api-network

networks:
  # create a network to allow client to request backend
  api-network:
    driver: bridge
