
CREATE APPLICATION ROLE app_public;
CREATE SCHEMA IF NOT EXISTS DEMO;
GRANT USAGE ON SCHEMA DEMO TO APPLICATION ROLE app_public;

-- create streamlit app entry point
CREATE STREAMLIT DEMO.my_app
  FROM '/streamlit'
  MAIN_FILE = '/main.py'
;
GRANT USAGE ON STREAMLIT DEMO.my_app TO APPLICATION ROLE app_public;

