FROM alpine:latest

# install python
RUN apk update
RUN apk add py-pip
RUN apk add --no-cache python3-dev 
RUN pip install --upgrade pip

# move contents
WORKDIR /working
COPY . /working

# install requirements
RUN pip --no-cache-dir install -r requirements.txt

# expose flask 8082 port for client
EXPOSE 8082

CMD ["python3", "src/app.py"]