version: '3.8'

services:
  backend:
    build: ./backend/
    container_name: flask-backend
    ports:
      - 8080:8080
    networks:
      - api-network
  client:
    build: ./client/
    container_name: flask-client
    environment:
      - URL=flask-backend  # same as the container_name in "services.backend"
    ports:
      - 8082:8082
    networks:
      - api-network

networks:
  api-network: 
    driver: bridge
  